# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sluice < Formula
  desc "A streaming log viewer with live filtering"
  homepage "https://github.com/MatthijsvanderPlas/Sluice"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.0/Sluice_Darwin_x86_64.tar.gz"
      sha256 "33302e1daa1d0cc1b0fc5f6971fc71775d6a086013cfa7de9c5176a10b44188b"

      define_method(:install) do
        bin.install "sluice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.0/Sluice_Darwin_arm64.tar.gz"
      sha256 "c47652b4b3d247fdb29cd85ab5a92750db3abaeffc6d5a386cdc375f787a3654"

      define_method(:install) do
        bin.install "sluice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.0/Sluice_Linux_x86_64.tar.gz"
      sha256 "9dbec935e872f60508a2da4988e3431f400bf5aac95a1578aade69cdf3074623"
      define_method(:install) do
        bin.install "sluice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.0/Sluice_Linux_arm64.tar.gz"
      sha256 "ab4bb2602c51bca4226a9f2cc49c9bf0b48f1cc851171b11d4dac37f990414b3"
      define_method(:install) do
        bin.install "sluice"
      end
    end
  end

  test do
    system "#{bin}/sluice", "--version"
  end
end
