# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sluice < Formula
  desc "A streaming log viewer with live filtering"
  homepage "https://github.com/MatthijsvanderPlas/Sluice"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.1/Sluice_Darwin_x86_64.tar.gz"
      sha256 "d299531ee120b44143d8c7838605f7e2c60cd2d01ea175cbe127991816185ee9"

      define_method(:install) do
        bin.install "sluice"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.1/Sluice_Darwin_arm64.tar.gz"
      sha256 "b3d0971b062a7744f2c4f2b703a39fd77217e4307bda998a9c19749a1beb2a27"

      define_method(:install) do
        bin.install "sluice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.1/Sluice_Linux_x86_64.tar.gz"
      sha256 "ee3e44450a5b575a3e72dcba9bd27897299f1b845d8f32e2cb94c5661aabb17c"
      define_method(:install) do
        bin.install "sluice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MatthijsvanderPlas/Sluice/releases/download/v0.1.1/Sluice_Linux_arm64.tar.gz"
      sha256 "53671f789174e427476bcc8e122044e3b97af917f8969b30e61f1d3a7fc4a5e6"
      define_method(:install) do
        bin.install "sluice"
      end
    end
  end

  test do
    system "#{bin}/sluice", "--version"
  end
end
